### ISSUE TITLE
Consider renaming this project

### ISSUE THREAD

**Issue by mattd** [davidgilbertson/peeping-dom#1]
The name of this project references an act related to stalking and assault, most commonly perpetrated by men on women. Consider choosing a different name.

**Comment by benschwarz** [comment]
I'd definitely like to add my voice here - Hard agree with @mattd. No finger pointing required - the library looks really interesting and I'm sure the project name was a bit of fun, but it perpetuates some rather insidious behaviour and it would be great to change the name.

**Comment by PengJiyuan** [comment]
dom-journey
